language: php
php: 
 - "5.4"
 - "7.0"
before_instal:
 - php /usr/bin/composer self-update
before_script:
 - composer install
script: ./vendor/bin/phpunit -- configuration phpunit.xml --coverage-text

