language: php
php:
 - "5.6"
before_instal:
 - php /usr/bin/composer self-update
before_script:
 - phpunit/composer install
script: phpunit --configuration phpunit/phpunit.xml --coverage-text
notifications:
  email: false
